#!/bin/bash
OUTFILE=tab-calls.js
cat src-last/backup-${OUTFILE} > ./${OUTFILE}

for xx in $(ls ./src-edited | grep -v @) ; do rm ./src-edited/$xx ; done
for xx in $(ls ./src-edited | grep @) ; do [[ -e ./src-edited/$xx/* ]] && rm ./src-edited/$xx/* ; done
